[greeter]
background=/usr/share/backgrounds/groovy-lightdm.png
user-background=false
theme-name=Groovy-LightDM
icon-theme-name=Gruvbox-Dark
cursor-theme-name=Adwaita
cursor-theme-size=28
font-name=JetBrainsMono Nerd Font 12
xft-antialias=true
xft-dpi=110
xft-hintstyle=slight
xft-rgba=rgb
active-monitor=#cursor
position=50% 52%
default-user-image=#avatar-default
hide-user-image=false
panel-position=top
clock-format=%a %d %b  ·  %I:%M %p
indicators=~host;~spacer;~clock;~spacer;~session;~power
transition-duration=280
transition-type=ease-in-out
screensaver-timeout=60
allow-debugging=false
